# ビルドステージ
FROM node:18-alpine AS builder

WORKDIR /app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY package*.json ./
RUN npm ci --include=dev

COPY . .
RUN npm run build
RUN npm run export

# 実行ステージ
FROM nginx:alpine AS runner
COPY --from=builder /app/out /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
